config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  namespace :api , defaults: {format: :json} do
      # resources :clients, only: [:index]
      post '/clients/set_locale' => 'clients#set_locale'
      get '/clients/:username' => 'clients#index'
      get '/clients/check_username/:username' => 'clients#check_username'
      resources :services, only: [:index]
      resources :subscription_services, only: [:index]
      resources :notifications
      post '/subscriptions/create'
      get '/subscriptions/approve'
      get '/subscriptions/cancel'
      get '/subscriptions/get_price/:service_id/:likes_count/:posts_count' => 'subscriptions#get_price'
      resources :subscriptions, only: [:show]

      post '/order_rows/create'
      post '/order_rows/create_stripe'
      get '/order_rows/approve'
      get '/order_rows/cancel'
      get '/order_rows/get_price/:service_id/:amounts' => 'order_rows#get_price'
      get '/order_rows/get_status/:order_code' => 'order_rows#get_status'
      resources :order_rows, only: [:show]
      resources :reviews, only: [:create]
      resources :newsletters, only: [:create]
      resources :statistics, only: [:index]
      namespace :mob do
        post '/clients/set_locale' => 'clients#set_locale'
        get '/clients/:username' => 'clients#index'
        get '/clients/check_username/:username' => 'clients#check_username'
        resources :services, only: [:index]
        resources :subscription_services, only: [:index]
        resources :notifications
        post '/subscriptions/create'
        get '/subscriptions/approve'
        get '/subscriptions/cancel'
        get '/subscriptions/get_price/:service_id/:likes_count/:posts_count' => 'subscriptions#get_price'
        resources :subscriptions, only: [:show]

        post '/order_rows/create'
        get '/order_rows/new'
        get '/order_rows/canceled'
        get '/order_rows/success'
        get '/order_rows/not_authorized'
        get '/order_rows/unknown'
        post '/order_rows/create_stripe'
        get '/order_rows/approve'
        get '/order_rows/cancel'
        get '/order_rows/get_price/:service_id/:amounts' => 'order_rows#get_price'
        get '/order_rows/get_status/:order_code' => 'order_rows#get_status'
        resources :order_rows, only: [:show]
        resources :reviews, only: [:create]
        resources :newsletters, only: [:create]
        resources :statistics, only: [:index]
      end
    end
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :api

  enum req_method: {GET: 0, POST: 1}
  enum service_family: {likes: 0, followers: 1, video_views: 2, comments: 3, custom_comments: 4}
end

app/controllers/api/mob/services_controller.rb
class Api::Mob::ServicesController < Api::ApiApplicationControllerController

  def index
    @services = Service.where(active: true).sort {|a, b| Service.service_families[a.service_family] <=> Service.service_families[b.service_family]}
  end
end

app/controllers/api/services_controller.rb
class Api::ServicesController < Api::ApiApplicationControllerController

  def index
    @services = Service.where(active: true).sort {|a, b| Service.service_families[a.service_family] <=> Service.service_families[b.service_family]}
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html {redirect_to @service, notice: 'Service was successfully created.'}
        format.json {render :show, status: :created, location: @service}
      else
        format.html {render :new}
        format.json {render json: @service.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html {redirect_to @service, notice: 'Service was successfully updated.'}
        format.json {render :show, status: :ok, location: @service}
      else
        format.html {render :edit}
        format.json {render json: @service.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html {redirect_to services_url, notice: 'Service was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:description, :s_type, :service_family, :minimum, :maximum, :price, :unit, :factor, :power, :intercept, :sale, :has_note, :note, :req_method, :active, :custom_comments_flag, :api_id)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% @service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :minimum %><br>
    <%= f.number_field :minimum %>
  </div>
  <div class="field">
    <%= f.label :maximum %><br>
    <%= f.number_field :maximum %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.number_field :unit %>
  </div>
  <div class="field">
    <%= f.label :factor %><br>
    <%= f.text_field :factor %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.text_field :power %>
  </div>
  <div class="field">
    <%= f.label :intercept %><br>
    <%= f.text_field :intercept %>
  </div>
  <div class="field">
    <%= f.label :sale %><br>
    <%= f.text_field :sale %>
  </div>
  <div class="field">
    <%= f.label :has_note %><br>
    <%= f.check_box :has_note %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :req_method %><br>
    <%= f.text_field :req_method %>
  </div>
  <div class="field">
    <%= f.label :service_family %><br>
    <%= f.text_field :service_family %>
  </div>
  <div class="field">
    <%= f.label :custom_comments_flag %><br>
    <%= f.check_box :custom_comments_flag %>
  </div>
  <div class="field">
    <%= f.label :api_id %><br>
    <%= f.text_field :api_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
  <tr>
    <th>Description</th>
    <th>Minimum</th>
    <th>Maximum</th>
    <th>Price</th>
    <th>Unit</th>
    <th>Factor</th>
    <th>Power</th>
    <th>Intercept</th>
    <th>Sale</th>
    <th>Has note</th>
    <th>Note</th>
    <th>Req method</th>
    <th>Service family</th>
    <th>Custom comments flag</th>
    <th>Api</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @services.each do |service| %>
    <tr>
      <td><%= service.description %></td>
      <td><%= service.minimum %></td>
      <td><%= service.maximum %></td>
      <td><%= service.price %></td>
      <td><%= service.unit %></td>
      <td><%= service.factor %></td>
      <td><%= service.power %></td>
      <td><%= service.intercept %></td>
      <td><%= service.sale %></td>
      <td><%= service.has_note %></td>
      <td><%= service.note %></td>
      <td><%= service.req_method %></td>
      <td><%= service.service_family %></td>
      <td><%= service.custom_comments_flag %></td>
      <td><%= service.api %></td>
      <td><%= link_to 'Show', service %></td>
      <td><%= link_to 'Edit', edit_service_path(service) %></td>
      <td><%= link_to 'Destroy', service, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Minimum:</strong>
  <%= @service.minimum %>
</p>

<p>
  <strong>Maximum:</strong>
  <%= @service.maximum %>
</p>

<p>
  <strong>Price:</strong>
  <%= @service.price %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @service.unit %>
</p>

<p>
  <strong>Factor:</strong>
  <%= @service.factor %>
</p>

<p>
  <strong>Power:</strong>
  <%= @service.power %>
</p>

<p>
  <strong>Intercept:</strong>
  <%= @service.intercept %>
</p>

<p>
  <strong>Sale:</strong>
  <%= @service.sale %>
</p>

<p>
  <strong>Has note:</strong>
  <%= @service.has_note %>
</p>

<p>
  <strong>Note:</strong>
  <%= @service.note %>
</p>

<p>
  <strong>Req method:</strong>
  <%= @service.req_method %>
</p>

<p>
  <strong>Service family:</strong>
  <%= @service.service_family %>
</p>

<p>
  <strong>Custom comments flag:</strong>
  <%= @service.custom_comments_flag %>
</p>

<p>
  <strong>Api:</strong>
  <%= @service.api %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>