config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  namespace :api , defaults: {format: :json} do
      # resources :clients, only: [:index]
      post '/clients/set_locale' => 'clients#set_locale'
      get '/clients/:username' => 'clients#index'
      get '/clients/check_username/:username' => 'clients#check_username'
      resources :services, only: [:index]
      resources :subscription_services, only: [:index]
      resources :notifications
      post '/subscriptions/create'
      get '/subscriptions/approve'
      get '/subscriptions/cancel'
      get '/subscriptions/get_price/:service_id/:likes_count/:posts_count' => 'subscriptions#get_price'
      resources :subscriptions, only: [:show]

      post '/order_rows/create'
      post '/order_rows/create_stripe'
      get '/order_rows/approve'
      get '/order_rows/cancel'
      get '/order_rows/get_price/:service_id/:amounts' => 'order_rows#get_price'
      get '/order_rows/get_status/:order_code' => 'order_rows#get_status'
      resources :order_rows, only: [:show]
      resources :reviews, only: [:create]
      resources :newsletters, only: [:create]
      resources :statistics, only: [:index]
      namespace :mob do
        post '/clients/set_locale' => 'clients#set_locale'
        get '/clients/:username' => 'clients#index'
        get '/clients/check_username/:username' => 'clients#check_username'
        resources :services, only: [:index]
        resources :subscription_services, only: [:index]
        resources :notifications
        post '/subscriptions/create'
        get '/subscriptions/approve'
        get '/subscriptions/cancel'
        get '/subscriptions/get_price/:service_id/:likes_count/:posts_count' => 'subscriptions#get_price'
        resources :subscriptions, only: [:show]

        post '/order_rows/create'
        get '/order_rows/new'
        get '/order_rows/canceled'
        get '/order_rows/success'
        get '/order_rows/not_authorized'
        get '/order_rows/unknown'
        post '/order_rows/create_stripe'
        get '/order_rows/approve'
        get '/order_rows/cancel'
        get '/order_rows/get_price/:service_id/:amounts' => 'order_rows#get_price'
        get '/order_rows/get_status/:order_code' => 'order_rows#get_status'
        resources :order_rows, only: [:show]
        resources :reviews, only: [:create]
        resources :newsletters, only: [:create]
        resources :statistics, only: [:index]
      end
    end
end

app/controllers/api/mob/newsletters_controller.rb
class Api::Mob::NewslettersController < Api::ApiApplicationControllerController

  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html {redirect_to @newsletter, notice: 'Newsletter was successfully created.'}
        format.json {render :show, status: :created, location: @newsletter}
      else
        format.html {render :new}
        format.json {render json: @newsletter.errors, status: :unprocessable_entity}
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def newsletter_params
    params.require(:newsletter).permit(:email)
  end
end

app/controllers/api/newsletters_controller.rb
class Api::NewslettersController < Api::ApiApplicationControllerController

  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html {redirect_to @newsletter, notice: 'Newsletter was successfully created.'}
        format.json {render :show, status: :created, location: @newsletter}
      else
        format.html {render :new}
        format.json {render json: @newsletter.errors, status: :unprocessable_entity}
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def newsletter_params
    params.require(:newsletter).permit(:email)
  end
end

app/views/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
        <% @newsletter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<h1>Editing Newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Newsletters</h1>

<table>
  <thead>
  <tr>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @newsletters.each do |newsletter| %>
    <tr>
      <td><%= newsletter.email %></td>
      <td><%= link_to 'Show', newsletter %></td>
      <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
      <td><%= link_to 'Destroy', newsletter, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsletter', new_newsletter_path %>

app/views/newsletters/new.html.erb
<h1>New Newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @newsletter.email %>
</p>

<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>