config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  namespace :api , defaults: {format: :json} do
      # resources :clients, only: [:index]
      post '/clients/set_locale' => 'clients#set_locale'
      get '/clients/:username' => 'clients#index'
      get '/clients/check_username/:username' => 'clients#check_username'
      resources :services, only: [:index]
      resources :subscription_services, only: [:index]
      resources :notifications
      post '/subscriptions/create'
      get '/subscriptions/approve'
      get '/subscriptions/cancel'
      get '/subscriptions/get_price/:service_id/:likes_count/:posts_count' => 'subscriptions#get_price'
      resources :subscriptions, only: [:show]

      post '/order_rows/create'
      post '/order_rows/create_stripe'
      get '/order_rows/approve'
      get '/order_rows/cancel'
      get '/order_rows/get_price/:service_id/:amounts' => 'order_rows#get_price'
      get '/order_rows/get_status/:order_code' => 'order_rows#get_status'
      resources :order_rows, only: [:show]
      resources :reviews, only: [:create]
      resources :newsletters, only: [:create]
      resources :statistics, only: [:index]
      namespace :mob do
        post '/clients/set_locale' => 'clients#set_locale'
        get '/clients/:username' => 'clients#index'
        get '/clients/check_username/:username' => 'clients#check_username'
        resources :services, only: [:index]
        resources :subscription_services, only: [:index]
        resources :notifications
        post '/subscriptions/create'
        get '/subscriptions/approve'
        get '/subscriptions/cancel'
        get '/subscriptions/get_price/:service_id/:likes_count/:posts_count' => 'subscriptions#get_price'
        resources :subscriptions, only: [:show]

        post '/order_rows/create'
        get '/order_rows/new'
        get '/order_rows/canceled'
        get '/order_rows/success'
        get '/order_rows/not_authorized'
        get '/order_rows/unknown'
        post '/order_rows/create_stripe'
        get '/order_rows/approve'
        get '/order_rows/cancel'
        get '/order_rows/get_price/:service_id/:amounts' => 'order_rows#get_price'
        get '/order_rows/get_status/:order_code' => 'order_rows#get_status'
        resources :order_rows, only: [:show]
        resources :reviews, only: [:create]
        resources :newsletters, only: [:create]
        resources :statistics, only: [:index]
      end
    end
end

app/controllers/api/mob/notifications_controller.rb
class Api::Mob::NotificationsController < Api::ApiApplicationControllerController
  def index
    @notifications = Notification.All
  end

  def show
    id = params[:id]
    @notification = Notification.find_by(id: id)
  end
end

app/controllers/api/notifications_controller.rb
class Api::NotificationsController < Api::ApiApplicationControllerController
  def index
    @notifications = Notification.All
  end

  def show
    id = params[:id]
    @notification = Notification.find_by(id: id)
  end
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
        <% @notification.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notifications</h1>

<table>
  <thead>
  <tr>
    <th>Text</th>
    <th>Active</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @notifications.each do |notification| %>
    <tr>
      <td><%= notification.text %></td>
      <td><%= notification.active %></td>
      <td><%= link_to 'Show', notification %></td>
      <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
      <td><%= link_to 'Destroy', notification, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @notification.text %>
</p>

<p>
  <strong>Active:</strong>
  <%= @notification.active %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>