config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  namespace :api , defaults: {format: :json} do
      # resources :clients, only: [:index]
      post '/clients/set_locale' => 'clients#set_locale'
      get '/clients/:username' => 'clients#index'
      get '/clients/check_username/:username' => 'clients#check_username'
      resources :services, only: [:index]
      resources :subscription_services, only: [:index]
      resources :notifications
      post '/subscriptions/create'
      get '/subscriptions/approve'
      get '/subscriptions/cancel'
      get '/subscriptions/get_price/:service_id/:likes_count/:posts_count' => 'subscriptions#get_price'
      resources :subscriptions, only: [:show]

      post '/order_rows/create'
      post '/order_rows/create_stripe'
      get '/order_rows/approve'
      get '/order_rows/cancel'
      get '/order_rows/get_price/:service_id/:amounts' => 'order_rows#get_price'
      get '/order_rows/get_status/:order_code' => 'order_rows#get_status'
      resources :order_rows, only: [:show]
      resources :reviews, only: [:create]
      resources :newsletters, only: [:create]
      resources :statistics, only: [:index]
      namespace :mob do
        post '/clients/set_locale' => 'clients#set_locale'
        get '/clients/:username' => 'clients#index'
        get '/clients/check_username/:username' => 'clients#check_username'
        resources :services, only: [:index]
        resources :subscription_services, only: [:index]
        resources :notifications
        post '/subscriptions/create'
        get '/subscriptions/approve'
        get '/subscriptions/cancel'
        get '/subscriptions/get_price/:service_id/:likes_count/:posts_count' => 'subscriptions#get_price'
        resources :subscriptions, only: [:show]

        post '/order_rows/create'
        get '/order_rows/new'
        get '/order_rows/canceled'
        get '/order_rows/success'
        get '/order_rows/not_authorized'
        get '/order_rows/unknown'
        post '/order_rows/create_stripe'
        get '/order_rows/approve'
        get '/order_rows/cancel'
        get '/order_rows/get_price/:service_id/:amounts' => 'order_rows#get_price'
        get '/order_rows/get_status/:order_code' => 'order_rows#get_status'
        resources :order_rows, only: [:show]
        resources :reviews, only: [:create]
        resources :newsletters, only: [:create]
        resources :statistics, only: [:index]
      end
    end
end

app/controllers/api/mob/subscriptions_controller.rb
class Api::Mob::SubscriptionsController < Api::ApiApplicationControllerController
  before_action :set_subscription, only: [:show]

  def show
  end

  def create
    subscription = SubscriptionGenerator.generate_subscription(params, request.remote_ip)
    subscription = Subscription.includes(:subscription_service).find(subscription.id)
    payment = PaymentGenerator.generate_sub_payment(subscription)
    if payment.create
      subscription.update(payment_id: payment.id)
      redirect_to payment.links.find {|v| v.method == "REDIRECT"}.href
    else
      redirect_to "#{APP_CONFIG['host']}/#{subscription.class.to_s.underscore.gsub('_', '-')}/-1"
    end
  end

  def approve
    payment_id = params["paymentId"]
    payer_id = params["PayerID"]
    payment = PaymentGenerator.get_payment(payment_id)
    subscription = Subscription.find_by(payment_id: payment_id)
    client = ClientService.add_client_if_not_exist(payer_id, payment)
    if !client.nil?
      if payment.state == 'created'
        payment.execute(payer_id: payer_id)
        if payment.state == 'approved'
          subscription.update(verified: true, client_id: client.id)
          redirect_to "#{APP_CONFIG['host']}/#{subscription.class.to_s.underscore.gsub('_', '-')}/#{subscription.id}"
        else
          redirect_to "#{APP_CONFIG['host']}/#{subscription.class.to_s.underscore.gsub('_', '-')}/-2"
        end
      else
        redirect_to "#{APP_CONFIG['host']}/#{subscription.class.to_s.underscore.gsub('_', '-')}/-1"
      end
    end
  end

  def cancel
    redirect_to "#{APP_CONFIG['host']}/#{Subscription.to_s.underscore.gsub('_', '-')}/-3"
  end

  def get_price
    service_id = params[:service_id]
    posts_coount = params[:posts_count]
    likes_count = params[:likes_count]
    @price = Price.calculate_sub_price(likes_count, posts_coount, service_id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/controllers/api/subscriptions_controller.rb
class Api::SubscriptionsController < Api::ApiApplicationControllerController
  before_action :set_subscription, only: [:show]

  def show
  end

  def create
    subscription = SubscriptionGenerator.generate_subscription(params, request.remote_ip)
    subscription = Subscription.includes(:subscription_service).find(subscription.id)
    payment = PaymentGenerator.generate_sub_payment(subscription)
    if payment.create
      subscription.update(payment_id: payment.id)
      redirect_to payment.links.find {|v| v.method == "REDIRECT"}.href
    else
      redirect_to "#{APP_CONFIG['host']}/#{subscription.class.to_s.underscore.gsub('_', '-')}/-1"
    end
  end

  def approve
    payment_id = params["paymentId"]
    payer_id = params["PayerID"]
    payment = PaymentGenerator.get_payment(payment_id)
    subscription = Subscription.find_by(payment_id: payment_id)
    client = ClientService.add_client_if_not_exist(payer_id, payment)
    if !client.nil?
      if payment.state == 'created'
        payment.execute(payer_id: payer_id)
        if payment.state == 'approved'
          subscription.update(verified: true, client_id: client.id)
          redirect_to "#{APP_CONFIG['host']}/#{subscription.class.to_s.underscore.gsub('_', '-')}/#{subscription.id}"
        else
          redirect_to "#{APP_CONFIG['host']}/#{subscription.class.to_s.underscore.gsub('_', '-')}/-2"
        end
      else
        redirect_to "#{APP_CONFIG['host']}/#{subscription.class.to_s.underscore.gsub('_', '-')}/-1"
      end
    end
  end

  def cancel
    redirect_to "#{APP_CONFIG['host']}/#{Subscription.to_s.underscore.gsub('_', '-')}/-3"
  end

  def get_price
    service_id = params[:service_id]
    posts_coount = params[:posts_count]
    likes_count = params[:likes_count]
    @price = Price.calculate_sub_price(likes_count, posts_coount, service_id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% @subscription.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :paid %><br>
    <%= f.text_field :paid %>
  </div>
  <div class="field">
    <%= f.label :net %><br>
    <%= f.text_field :net %>
  </div>
  <div class="field">
    <%= f.label :order_code %><br>
    <%= f.text_field :order_code %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br>
    <%= f.text_field :transaction_id %>
  </div>
  <div class="field">
    <%= f.label :payment_id %><br>
    <%= f.text_field :payment_id %>
  </div>
  <div class="field">
    <%= f.label :posts_count %><br>
    <%= f.number_field :posts_count %>
  </div>
  <div class="field">
    <%= f.label :likes_count %><br>
    <%= f.number_field :likes_count %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :client_ip %><br>
    <%= f.text_field :client_ip %>
  </div>
  <div class="field">
    <%= f.label :verified %><br>
    <%= f.check_box :verified %>
  </div>
  <div class="field">
    <%= f.label :created_by_admin %><br>
    <%= f.check_box :created_by_admin %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :subscription_service_id %><br>
    <%= f.text_field :subscription_service_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subscriptions</h1>

<table>
  <thead>
  <tr>
    <th>Username</th>
    <th>Paid</th>
    <th>Net</th>
    <th>Order code</th>
    <th>Transaction</th>
    <th>Payment</th>
    <th>Posts count</th>
    <th>Likes count</th>
    <th>Status</th>
    <th>Client ip</th>
    <th>Verified</th>
    <th>Created by admin</th>
    <th>Client</th>
    <th>Subscription service</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @subscriptions.each do |subscription| %>
    <tr>
      <td><%= subscription.username %></td>
      <td><%= subscription.paid %></td>
      <td><%= subscription.net %></td>
      <td><%= subscription.order_code %></td>
      <td><%= subscription.transaction_id %></td>
      <td><%= subscription.payment_id %></td>
      <td><%= subscription.posts_count %></td>
      <td><%= subscription.likes_count %></td>
      <td><%= subscription.status %></td>
      <td><%= subscription.client_ip %></td>
      <td><%= subscription.verified %></td>
      <td><%= subscription.created_by_admin %></td>
      <td><%= subscription.client %></td>
      <td><%= subscription.subscription_service %></td>
      <td><%= link_to 'Show', subscription %></td>
      <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
      <td><%= link_to 'Destroy', subscription, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @subscription.username %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @subscription.paid %>
</p>

<p>
  <strong>Net:</strong>
  <%= @subscription.net %>
</p>

<p>
  <strong>Order code:</strong>
  <%= @subscription.order_code %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @subscription.transaction_id %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @subscription.payment_id %>
</p>

<p>
  <strong>Posts count:</strong>
  <%= @subscription.posts_count %>
</p>

<p>
  <strong>Likes count:</strong>
  <%= @subscription.likes_count %>
</p>

<p>
  <strong>Status:</strong>
  <%= @subscription.status %>
</p>

<p>
  <strong>Client ip:</strong>
  <%= @subscription.client_ip %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @subscription.verified %>
</p>

<p>
  <strong>Created by admin:</strong>
  <%= @subscription.created_by_admin %>
</p>

<p>
  <strong>Client:</strong>
  <%= @subscription.client %>
</p>

<p>
  <strong>Subscription service:</strong>
  <%= @subscription.subscription_service %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>